// apps/web-legacy/src/components/global-command.tsx
import { useNavigate, useRouterState } from '@tanstack/react-router'
import { FileVideoIcon, LayoutGridIcon, SearchIcon } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from '@/components/ui/command'
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog'
import { getDavisSearchSuggestions } from '@/features/davis/davis.functions'
import { getTheoSearchSuggestions } from '@/features/theo/theo.functions'

type SearchResults = {
  videos: { videoId: string; title: string }[]
  sponsors: { sponsorId: string; name: string; slug: string }[]
}

const emptyResults: SearchResults = { videos: [], sponsors: [] }

const useDebouncedValue = (value: string, delayMs: number) => {
  const [debounced, setDebounced] = useState(value)
  useEffect(() => {
    const timer = setTimeout(() => setDebounced(value), delayMs)
    return () => clearTimeout(timer)
  }, [value, delayMs])
  return debounced
}

type Props = {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export const GlobalCommand = ({ open, onOpenChange }: Props) => {
  const navigate = useNavigate()
  const location = useRouterState({ select: (s) => s.location })
  const [query, setQuery] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [results, setResults] = useState<SearchResults>(emptyResults)
  const cancelRef = useRef(false)

  const channel = location.pathname.startsWith('/davis')
    ? 'davis'
    : location.pathname.startsWith('/theo')
      ? 'theo'
      : null

  const debouncedQuery = useDebouncedValue(query, 180)

  useEffect(() => {
    const q = debouncedQuery.trim()
    if (q.length < 2 || !channel) {
      setResults(emptyResults)
      return
    }

    cancelRef.current = false
    setIsLoading(true)

    const searchFn =
      channel === 'davis' ? getDavisSearchSuggestions : getTheoSearchSuggestions

    searchFn({ data: { q } })
      .then((result) => {
        if (cancelRef.current) return
        if (result.status === 'ok') {
          setResults(result.data)
        } else {
          setResults(emptyResults)
        }
      })
      .finally(() => {
        if (!cancelRef.current) setIsLoading(false)
      })

    return () => {
      cancelRef.current = true
    }
  }, [debouncedQuery, channel])

  const handleClose = () => {
    onOpenChange(false)
    setQuery('')
    setResults(emptyResults)
  }

  const handleOpenChange = (val: boolean) => {
    if (!val) handleClose()
    else onOpenChange(true)
  }

  const goToVideo = (videoId: string) => {
    const base = channel === 'davis' ? '/davis/video/$id' : '/theo/video/$id'
    navigate({
      to: base,
      params: { id: videoId },
      search: { commentsPage: 1 },
    })
    handleClose()
  }

  const goToSponsor = (slug: string) => {
    const base = channel === 'davis' ? '/davis/sponsor/$id' : '/theo/sponsor/$id'
    navigate({ to: base, params: { id: slug }, search: { page: 1 } })
    handleClose()
  }

  const hasResults =
    results.videos.length > 0 || results.sponsors.length > 0

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="overflow-hidden p-0 shadow-2xl sm:max-w-xl">
        <DialogTitle className="sr-only">Search</DialogTitle>
        <Command shouldFilter={false} className="[&_[cmdk-group-heading]]:text-muted-foreground [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:font-medium">
          <CommandInput
            placeholder="Search videos, sponsors..."
            value={query}
            onValueChange={setQuery}
          />
          <CommandList className="max-h-[420px]">
            {isLoading ? (
              <CommandEmpty>Searching...</CommandEmpty>
            ) : query.length >= 2 && !hasResults ? (
              <CommandEmpty>No results found.</CommandEmpty>
            ) : null}

            {query.length === 0 && (
              <CommandGroup heading="Channels">
                <CommandItem
                  onSelect={() => {
                    navigate({ to: '/theo', search: { page: 1, q: undefined } })
                    handleClose()
                  }}
                >
                  <LayoutGridIcon />
                  Theo's Channel
                </CommandItem>
                <CommandItem
                  onSelect={() => {
                    navigate({ to: '/davis', search: { page: 1, q: undefined } })
                    handleClose()
                  }}
                >
                  <LayoutGridIcon />
                  Davis's Channel
                </CommandItem>
              </CommandGroup>
            )}

            {!isLoading && results.videos.length > 0 && (
              <>
                {query.length === 0 && <CommandSeparator />}
                <CommandGroup heading="Videos">
                  {results.videos.map((video) => (
                    <CommandItem
                      key={video.videoId}
                      value={video.videoId}
                      onSelect={() => goToVideo(video.videoId)}
                    >
                      <FileVideoIcon />
                      {video.title}
                    </CommandItem>
                  ))}
                </CommandGroup>
              </>
            )}

            {!isLoading && results.sponsors.length > 0 && (
              <>
                <CommandSeparator />
                <CommandGroup heading="Sponsors">
                  {results.sponsors.map((sponsor) => (
                    <CommandItem
                      key={sponsor.sponsorId}
                      value={sponsor.sponsorId}
                      onSelect={() => goToSponsor(sponsor.slug)}
                    >
                      <SearchIcon />
                      {sponsor.name}
                    </CommandItem>
                  ))}
                </CommandGroup>
              </>
            )}
          </CommandList>
        </Command>
      </DialogContent>
    </Dialog>
  )
}

// apps/web/src/lib/components/GlobalCommand.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import ArrowRightIcon from '@lucide/svelte/icons/arrow-right'
  import PlayIcon from '@lucide/svelte/icons/play'
  import MegaphoneIcon from '@lucide/svelte/icons/megaphone'
  import { getDavisSearchSuggestions } from '@/remote/davis.remote'
  import { getTheoSearchSuggestions } from '@/remote/theo.remote'
  import { toHref } from '@/utils/url'
  import * as Command from '@/components/ui/command/index.js'

  type SearchResults = {
    videos: { videoId: string; title: string }[]
    sponsors: { sponsorId: string; name: string; slug: string }[]
  }

  const emptyResults: SearchResults = { videos: [], sponsors: [] }

  let { open = $bindable(false) } = $props<{ open: boolean }>()

  let inputValue = $state('')
  let debouncedQuery = $state('')
  let isLoading = $state(false)
  let results = $state<SearchResults>(emptyResults)

  const channel = $derived(
    page.url.pathname.startsWith('/davis')
      ? 'davis'
      : page.url.pathname.startsWith('/theo')
        ? 'theo'
        : null,
  )

  const showChannelPicker = $derived(inputValue.trim().length === 0)
  const hasResults = $derived(
    results.videos.length > 0 || results.sponsors.length > 0,
  )

  const openChannel = async (next: 'theo' | 'davis') => {
    await goto(toHref(`/${next}`, { page: 1 }))
    open = false
    inputValue = ''
  }

  const goToVideo = async (videoId: string) => {
    await goto(toHref(`/${channel}/video/${encodeURIComponent(videoId)}`, { commentsPage: 1 }))
    open = false
    inputValue = ''
  }

  const goToSponsor = async (slug: string) => {
    await goto(toHref(`/${channel}/sponsor/${encodeURIComponent(slug)}`, { page: 1 }))
    open = false
    inputValue = ''
  }

  $effect(() => {
    const nextQuery = inputValue
    const timer = setTimeout(() => {
      debouncedQuery = nextQuery
    }, 180)
    return () => clearTimeout(timer)
  })

  $effect(() => {
    const q = debouncedQuery.trim()

    if (!open || !channel || q.length < 2) {
      results = emptyResults
      isLoading = false
      return
    }

    let cancelled = false
    isLoading = true

    const searchFn = channel === 'davis' ? getDavisSearchSuggestions : getTheoSearchSuggestions

    searchFn({ q })
      .then((result) => {
        if (cancelled) return
        if (result.status === 'ok') {
          results = result.data
        } else {
          results = emptyResults
        }
      })
      .catch(() => {
        if (!cancelled) results = emptyResults
      })
      .finally(() => {
        if (!cancelled) isLoading = false
      })

    return () => {
      cancelled = true
    }
  })
</script>

<Command.Dialog
  bind:open
  shouldFilter={false}
  onOpenChange={(next) => {
    open = next
    if (!next) {
      inputValue = ''
      debouncedQuery = ''
      results = emptyResults
      isLoading = false
    }
  }}
  title="Search"
  description="Search videos and sponsors"
>
  <Command.Input
    value={inputValue}
    oninput={(event: Event) => {
      inputValue = (event.currentTarget as HTMLInputElement | null)?.value ?? ''
    }}
    placeholder="Search videos, sponsors..."
  />
  <Command.List class="min-h-[300px]">
    {#if showChannelPicker}
      <Command.Group heading="Channels">
        <Command.Item onSelect={() => openChannel('theo')}>
          <ArrowRightIcon />
          <span>Theo's Channel</span>
        </Command.Item>
        <Command.Item onSelect={() => openChannel('davis')}>
          <ArrowRightIcon />
          <span>Davis's Channel</span>
        </Command.Item>
      </Command.Group>
    {:else if !hasResults && !isLoading}
      <Command.Empty>No results found.</Command.Empty>
    {:else}
      {#if results.videos.length > 0}
        <Command.Group heading="Videos">
          {#each results.videos as video (video.videoId)}
            <Command.Item value={video.videoId} onSelect={() => goToVideo(video.videoId)}>
              <PlayIcon />
              <span>{video.title}</span>
            </Command.Item>
          {/each}
        </Command.Group>
      {/if}
      {#if results.sponsors.length > 0}
        <Command.Separator />
        <Command.Group heading="Sponsors">
          {#each results.sponsors as sponsor (sponsor.sponsorId)}
            <Command.Item value={sponsor.sponsorId} onSelect={() => goToSponsor(sponsor.slug)}>
              <MegaphoneIcon />
              <span>{sponsor.name}</span>
            </Command.Item>
          {/each}
        </Command.Group>
      {/if}
    {/if}
  </Command.List>
</Command.Dialog>
